version: '3'
services:

  trader:
      container_name: baibai-trader
      build: ./baibai-trader
      volumes:
        - logs:/baibaitrader/log_files

  server:
    container_name: baibai-server
    build: ./baibai-server
    ports:
      - "8080:8080"
    volumes:
      - logs:/log_files
    depends_on:
      - trader

  web:
    container_name: baibai-watcher
    build: ./baibai-watcher
    ports:
      - "3000:3000"
    volumes:
      - $PWD/baibai-watcher /baibai-watcher
    depends_on:
      - server

volumes:
  logs: